### ISSUE TITLE
Create Basic React Project Structure for Frontend

### ISSUE THREAD

**Issue by artemis-i-guess** [artemis-i-guess/Flash-Cards#2]
Remember to include all components, pages, api directories/files you think will be needed for the same.

**Comment by CS-parth** [comment]
Can this be assigned!

**Comment by artemis-i-guess** [comment]
@CS-parth  yeah sure. do follow the rules while PR.

**Comment by kous27** [comment]
Bhaiya please assign the issue to me.
Email - kousthav.sarkar@gmail.com

**Comment by artemis-i-guess** [comment]
sure
